services:
  postgres:
    image: "postgres:16"
    restart: unless-stopped
    environment:
      - "POSTGRES_DB=movieverse"
      - "POSTGRES_PASSWORD=123456"
      - "POSTGRES_USER=postgres"
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
